# Generated by Django 5.0.6 on 2024-06-24 08:17

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('themename', models.TextField()),
                ('themecontent', ckeditor.fields.RichTextField()),
                ('themeimg', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('themeauthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commentcontent', ckeditor.fields.RichTextField()),
                ('comment_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('commentimg', models.ImageField(upload_to='img/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genshinapp.themes')),
            ],
        ),
    ]
